#!/bin/bash

if [ -d $HOME/po4a ]
then
    rm -rf $HOME/po4a
fi

if [ -f $HOME/po4a_*_amd64.deb ] ; then
    rm $HOME/po4a_*_amd64.deb
fi

cd $HOME

git clone -b deb-build --single-branch git@github.com:ignotus666/po4a.git

cd $HOME/po4a

DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -rfakeroot -us -uc -b

cd $HOME

rm po4a_*.tar.xz
rm po4a_*amd64.buildinfo
rm po4a_*amd64.changes

sudo dpkg -i $HOME/po4a_*_amd64.deb

if [ -d $HOME/po4a ]
then
    rm -rf $HOME/po4a
fi

dialog --title "po4a installation" --msgbox "po4a installed!" 0 0
