#!/bin/sh

$HOME/scripts/misc/SMT_performance_on.sh &

# /home/daryl/audiorelay/opt/audiorelay/bin/AudioRelay &

pw-metadata -n settings 0 clock.force-quantum 48 &
pw-metadata -n settings 0 clock.force-rate 48000 &

qpwgraph -a -x -m $HOME/qpwgraph_patchbays/Pipewire_guitar_THU.qpwgraph &

sleep 2

carla $HOME/carla_projects/guitar_THU.carxp &

# slgui --load-session=$HOME/sooperlooper_presets/pedalboard.slsess &

jack_mixer --config=$HOME/jack_mixer_configs/Guitar &&

pw-metadata -n settings 0 clock.force-quantum 512 &&

qpwgraph -d -n -m $HOME/qpwgraph_patchbays/Pipewire_guitar_THU.qpwgraph &&

sudo $HOME/scripts/misc/smt-manager.pl --online; sudo cpupower-gui pr Schedutil
