#!/bin/sh

/usr/bin/qjackctl --preset=Jamulus --active-patchbay=$HOME/jack_patchbays/Jamulus+TH-U.xml &

sleep 5


env WINEPREFIX="$HOME/.wine" /opt/wine-staging/bin/wine C:\\Program\ Files\\Overloud\\TH-U\ Slate\ Edition\\TH-U\ Slate-64.exe &

jamulus -s -F &

sleep 2

jamulus --ctrlmidich "1;70" &

sleep 2


jack_mixer --config=$HOME/jack_mixer_configs/Guitar &

sleep 5

#jack_disconnect 'TH-U Slate-64:out_1' system:playback_1
#jack_disconnect 'TH-U Slate-64:out_2' system:playback_2
jack_disconnect system:capture_1 'Jamulus:input left'
jack_disconnect system:capture_2 'Jamulus:input right'
