#!/bin/bash

if [ -d $HOME/jamulus ]
then
    rm -rf $HOME/jamulus
fi

if [ -f $HOME/jamulus_*.deb ]
then
    rm $HOME/jamulus_*.deb
fi

cd $HOME

wait 4

git clone https://github.com/jamulussoftware/jamulus.git

cp  -r ~/imágenes/jamulus_pngs/*.png ~/jamulus/src/res/

cd $HOME/jamulus/distributions/

$HOME/jamulus/distributions/build-debian-package-auto.sh

rm $HOME/jamulus_*.buildinfo
rm $HOME/jamulus_*.changes
rm $HOME/jamulus-headless_*.deb
rm $HOME/jamulus_*.build

sudo dpkg -i $HOME/jamulus_*.deb

#dialog --title "Jamulus installation" --msgbox "Jamulus installed!" 0 0
