#!/bin/bash

cd $HOME/jamulus/distributions/

$HOME/jamulus/distributions/build-debian-package-auto.sh

cd $HOME

rm jamulus_*.buildinfo
rm jamulus_*.changes

sudo dpkg -i ~/jamulus_*.deb

dialog --title "Jamulus installation" --msgbox "Jamulus installed!" 0 0
