#!/bin/sh

if [ -d $HOME/jamulus ]
then
    rm -rf $HOME/jamulus
fi

cd $HOME

#git clone https://github.com/corrados/jamulus.git &&
git clone -b my-build --single-branch https://github.com/ignotus666/jamulus.git
