#!/bin/sh

/usr/bin/qjackctl --preset=Jamulus --active-patchbay=/home/daryl/jack_patchbays/Jamulus+TH-U.xml &

sleep 5

jamulus -s -F &

sleep 2

jamulus --ctrlmidich "1;70" &

sleep 2

env WINEPREFIX="/home/daryl/.wine" /opt/wine-staging/bin/wine C:\\Program\ Files\\Overloud\\TH-U\\TH-U-64.exe  &


jack_mixer --config=/home/daryl/jack_mixer_configs/Guitar &

sleep 15

jack_disconnect TH-U-64:out_1 system:playback_1
jack_disconnect TH-U-64:out_2 system:playback_2
jack_disconnect system:capture_1 'Jamulus:input left'
jack_disconnect system:capture_2 'Jamulus:input right'

