#!/bin/sh

/usr/bin/qjackctl --preset=superior_solo --active-patchbay=$HOME/jack_patchbays/superior_solo.xml &

env WINEPREFIX="$HOME/.wine" /opt/wine-staging/bin/wine C:\\Program\ Files\\Toontrack\\Superior\ Drummer\\Superior\ Drummer\ 3.exe &

sleep 2

jack_mixer --config=$HOME/jack_mixer_configs/superior_solo &

sleep 40

jack_disconnect 'Superior Drummer 3:out_1' system:playback_1
jack_disconnect 'Superior Drummer 3:out_2' system:playback_2
jack_disconnect system:capture_1 'Superior Drummer 3:in_1'
jack_disconnect system:capture_2 'Superior Drummer 3:in_2'
jack_disconnect 'PulseAudio JACK Sink:front-left' system:playback_1
jack_disconnect 'PulseAudio JACK Sink:front-right' system:playback_2
