#!/bin/sh

/usr/bin/qjackctl --preset=superior_solo --active-patchbay=/home/daryl/jack_patchbays/superior_solo_eq.xml &

sleep 2

env WINEPREFIX="/home/daryl/.wine" /opt/wine-stable/bin/wine C:\\Program\ Files\\Toontrack\\Superior\ Drummer\\Superior\ Drummer\ 3.exe &

carla /home/daryl/carla_projects/superior_drummer_3.carxp &

jack_mixer --config=/home/daryl/jack_mixer_configs/superior_solo
