#!/bin/sh

/usr/bin/qjackctl --preset=superior_solo_eq --active-patchbay=$HOME/jack_patchbays/superior_solo_eq.xml &

sleep 2

env WINEPREFIX="$HOME/.wine" /opt/wine-staging/bin/wine C:\\Program\ Files\\Toontrack\\Superior\ Drummer\\Superior\ Drummer\ 3.exe &

carla $HOME/carla_projects/superior_drummer_3.carxp &

jack_mixer --config=$HOME/jack_mixer_configs/superior_solo

sleep 40

jack_disconnect 'jack_mixer:superior_in Out L' 'EQ10Q Stereo:Input1'
jack_disconnect 'jack_mixer:superior_in Out R' 'EQ10Q Stereo:Input2'
