#!/bin/sh


if [ -d $HOME/ardour ]
then
    rm -rf $HOME/ardour
fi

cd $HOME

git clone git://github.com/Ardour/ardour

#sudo apt-get build-dep ardour
# except debian does not [yet] list libreadline as build-dependency
#sudo apt-get install libreadline-dev

cd ardour

./waf configure --optimize

./waf

#sudo ./waf install
#./gtk2_ardour/ardev
