#!/bin/bash

if [ -d $HOME/jack_mixer ]
then
    rm -rf $HOME/jack_mixer
fi

if [ -f $HOME/jack-mixer_*.deb ] ; then
    rm $HOME/jack-mixer_*.deb
fi

cd $HOME

git clone -b deb-build --single-branch git@github.com:ignotus666/jack_mixer.git

cd $HOME/jack_mixer

  if sed -i -e \
     's|import sys$|import sys, sysconfig\nsys.path.insert(0, sysconfig.get_path("purelib"))|' \
     jack_mixer/__main__.py ; then
      echo "Edited the jack_mixer start script to let it find the jack_mixer module"
  else
      echo "Couldn't edit the jack_mixer start script to let it find the jack_mixer module"
  fi

dh_make --createorig -p jack-mixer_17

dh_auto_configure --buildsystem=meson

dpkg-buildpackage -rfakeroot -us -uc -b

cd $HOME

rm jack-mixer_*.tar.xz
rm jack-mixer_*amd64.buildinfo
rm jack-mixer_*amd64.changes
rm jack-mixer-dbgsym_*.ddeb

sudo dpkg -i $HOME/jack-mixer_*.deb

if [ -d $HOME/jack_mixer ]
then
    rm -rf $HOME/jack_mixer
fi

echo ''
echo "Jack-Mixer installed!"
