#!/bin/bash
#Simple Yad Frontend to set Pipewire metadata
#broken out from AVLinux PipeWire Tools

buffer=\
`yad\
 --entry\
 --height=128\
 --width=400\
 --center\
 --title="PipeWire Metadata Quantum Settings"\
 --window-icon=preferences\
 --text="<b>Enter new buffer size.</b>\n Suggested values are:\n 64|128|256|512|1024|2048"\
 --text-align=left`\

pw-metadata -n settings 0 clock.force-quantum $buffer

samplerate=\
`yad\
 --entry\
 --height=128\
 --width=400\
 --center\
 --title="PipeWire Metadata Sample Rate Settings"\
 --window-icon=preferences\
 --text="<b>Enter new sample rate.</b>\n Suggested values are:\n 44100|48000|88200|96000"\
 --text-align=left`\

pw-metadata -n settings 0 clock.force-rate $samplerate


pw-metadata -n settings 2>&1 | yad --text-info --width=540 --height=220 --center --window-icon=preferences --title="Current PipeWire Metadata Settings"

exit
