#!/bin/bash

if [ -d $HOME/sooperlooper ]
then
    rm -rf $HOME/sooperlooper
fi

if [ -f $HOME/sooperlooper.deb ] ; then
    rm $HOME/sooperlooper.deb
fi

cd $HOME

git clone -b deb-build --single-branch git@github.com:ignotus666/sooperlooper.git

cd $HOME/sooperlooper

$HOME/sooperlooper/autogen.sh

$HOME/sooperlooper/configure

make

sudo make install

#rm -f ./.gitignore
#rm -f ./.travis.yml
#rm -f ./COPYING



#dpkg-deb --build $HOME/sooperlooper

#cd $HOME

#sudo dpkg -i $HOME/sooperlooper.deb

if [ -d $HOME/sooperlooper ]
then
    rm -rf $HOME/sooperlooper
fi

dialog --title "Sooperlooper installation" --msgbox "Sooperlooper installed!" 0 0
