#!/bin/bash

if [ -d ~/sooperlooper ]
then
    rm -rf ~/sooperlooper
fi

if [ -f ~/sooperlooper.deb ] ; then
    rm ~/sooperlooper.deb
fi

cd ~

git clone -b deb-build --single-branch git@github.com:ignotus666/sooperlooper.git

cd ~/sooperlooper

rm -f ./.gitignore
rm -f ./.travis.yml
rm -f ./COPYING

dpkg-deb --build ~/sooperlooper

cd ~

sudo dpkg -i ~/sooperlooper.deb

if [ -d ~/sooperlooper ]
then
    rm -rf ~/sooperlooper
fi

dialog --title "Sooperlooper installation" --msgbox "Sooperlooper installed!" 0 0
