#!/bin/bash

cd $HOME/jamulus/

$HOME/jamulus/linux/deploy_deb.sh

cd $HOME

rm jamulus_*.buildinfo
rm jamulus_*.changes

sudo dpkg -i ~/jamulus_*.deb

dialog --title "Jamulus installation" --msgbox "Jamulus installed!" 0 0
