#!/bin/bash

cd $HOME/jamulus_app/jamulus

if [ -f $HOME/jamulus_app/jamulus_*.deb ]
then
    rm $HOME/jamulus_app/jamulus_*.deb
fi

$HOME/jamulus_app/jamulus/linux/deploy_deb.sh

rm $HOME/jamulus_app/jamulus_*.buildinfo
rm $HOME/jamulus_app/jamulus_*.changes
rm $HOME/jamulus_app/jamulus_*.build

sudo dpkg -i $HOME/jamulus_app/jamulus_*.deb

dialog --title "Jamulus installation" --msgbox "Jamulus installed!" 0 0
