#!/bin/bash

cd $HOME/jamulus/

$HOME/jamulus/linux/deploy_deb.sh

rm $HOME/jamulus_*.buildinfo
rm $HOME/jamulus_*.changes
rm $HOME/jamulus_*.build

sudo dpkg -i $HOME/jamulus_*.deb

dialog --title "Jamulus installation" --msgbox "Jamulus installed!" 0 0
