#!/bin/sh

if [ -d $HOME/jamulus_app/jamulus ]
then
    rm -rf $HOME/jamulus_app/jamulus
fi

cd $HOME/jamulus_app

#git clone https://github.com/corrados/jamulus.git &&
git clone -b my-build --single-branch https://github.com/ignotus666/jamulus.git
